name = "sikhiya-backend-worker"
main = "worker.ts"
compatibility_date = "2026-02-04"

[[d1_databases]]
binding = "DB"
database_name = "sikhiya_connect"
database_id = "99d59259-8849-40d5-96da-9e89fa84631b"

[vars]
SECRET_KEY = "sikhiya_2026_u9Vx3QkP7mT2zL8rA5nG1hJ6wD0sC4eB"
ADMIN_EMAIL = "sikhiyaconnect@gmail.com"
ADMIN_PASSWORD = "admin@sikhiya007"
ADMIN_NAME = "Sikhiya Admin"
DEV_OTP_RETURN = "false"
